#!usr/bin/python

#########################
#      Getting the user input
#      Name: Mercy Muiruri
#      Date: 18/5/22 
##########################

# getting user input

f_name = input("What is your name ? ")
print(" My name is " + f_name)
print(f_name)

age = input( "How old are you ?")
print(" you are " + str(age) + " years old ")

myFavouriteFood = input( "What is your favourite food ")
print("Your favourite food is " + myFavouriteFood)

schoolAttended = input( "Which school did you attend ?")
print(" You attended " + schoolAttended)